#!/usr/bin/env python3
"""session_bylines.py: Recognize Claude session-URL bylines in GitHub content.

`strip_session_bylines.py` repairs bylines after the fact, from a webhook.
`scripts/agents/verify_github_write.py` has to recognize the same bylines at
write time, so it can subtract them before diffing sent text against stored
text.  This module holds the pattern and the one function both need, so the
two callers share a definition instead of drifting apart.

It deliberately imports nothing outside the standard library.  The write-time
caller runs inside a Claude Code hook, where a missing third-party package
would turn a check into a crash.

This module has no `main`; it is imported, not run directly.
"""

import re

# Regex matching every occurrence of a Claude session-URL byline.
# Two forms are matched:
#
#   Bare URL (preceded by a newline):
#       \nhttps://claude.ai/code/session_<token>
#
#   Markdown-link footer (the form Claude agents actually emit):
#       \n_Generated by [Claude Code](https://claude.ai/code[/session_<token>])_
#
#   The Markdown-link footer's URL may end at "code" or continue with a
#   "/session_<token>" suffix; both are stripped (see issue #377).
#
#   The Markdown-link footer may optionally be preceded by a \n--- separator
#   line (e.g. when the agent appended "---\n_Generated by ..._" at the end of
#   a body).  The separator is consumed along with the footer so no orphaned
#   "---" is left behind.
BYLINE_RE = re.compile(
    r"\n(?:---\n)?_Generated by \[Claude Code\]\(https://claude\.ai/code(?:/session_\S+)?\)_"
    r"|"
    r"\nhttps://claude\.ai/code/session_\S+"
)


def strip_bylines(text: str) -> str:
    """Return *text* with all Claude session-URL bylines removed."""
    return BYLINE_RE.sub("", text)
