#!/usr/bin/env python3
"""Unit tests for audit_requirements.py.

No test reaches the network: pip-audit is replaced by a fake runner that
answers from a table of package name -> advisories, so the tests exercise the
parsing, ignore-matching and verdict logic rather than the vulnerability feed.
"""

import io
import os
import subprocess
import sys
import tempfile
import unittest
import unittest.mock
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
import audit_requirements as ar  # noqa: E402


def fake_runner(vulns_by_package: dict[str, list[dict]]):
    """Return a pip-audit stand-in that reports *vulns_by_package* for the pins it is given."""

    def run(requirements: str) -> dict:
        dependencies = []
        for line in requirements.splitlines():
            name, _, version = line.partition("==")
            dependencies.append(
                {
                    "name": name,
                    "version": version,
                    "vulns": vulns_by_package.get(name, []),
                }
            )
        return {"dependencies": dependencies, "fixes": []}

    return run


def vuln(vuln_id: str, fix: str = "9.9.9", aliases: tuple[str, ...] = ()) -> dict:
    return {"id": vuln_id, "fix_versions": [fix], "aliases": list(aliases)}


class TestNormalize(unittest.TestCase):
    def test_pep503_normalization(self):
        self.assertEqual(ar.normalize("Mdformat_GFM"), "mdformat-gfm")
        self.assertEqual(ar.normalize("ruamel.yaml"), "ruamel-yaml")
        self.assertEqual(ar.normalize("rpds-py"), "rpds-py")


class TestParsePins(unittest.TestCase):
    def test_reads_pins_and_skips_hashes_and_comments(self):
        text = (
            "# This file was autogenerated by uv\n"
            "certifi==2026.6.17 \\\n"
            "    --hash=sha256:abc \\\n"
            "    --hash=sha256:def\n"
            "    # via requests\n"
            "requests==2.34.2 \\\n"
            "    --hash=sha256:012\n"
        )
        self.assertEqual(
            ar.parse_pins(text, "lock.txt"),
            [ar.Pin("certifi", "2026.6.17"), ar.Pin("requests", "2.34.2")],
        )

    def test_marker_gated_pins_are_included(self):
        # The whole point of re-deriving the pin list: pip-audit would evaluate
        # these markers against the running interpreter and skip both.
        text = (
            "pywin32==311 ; sys_platform == 'win32' \\\n"
            "    --hash=sha256:abc\n"
            "tomli==2.4.1 ; python_full_version < '3.11' \\\n"
            "    --hash=sha256:def\n"
        )
        self.assertEqual(
            ar.parse_pins(text, "lock.txt"),
            [ar.Pin("pywin32", "311"), ar.Pin("tomli", "2.4.1")],
        )

    def test_names_are_normalized_and_duplicates_collapsed(self):
        text = "Ruamel.YAML==0.19.1\nruamel-yaml==0.19.1\n"
        self.assertEqual(ar.parse_pins(text, "lock.txt"), [ar.Pin("ruamel-yaml", "0.19.1")])

    def test_unrecognized_top_level_line_is_an_error(self):
        # Failing closed keeps a lock-format change from silently shrinking coverage.
        with self.assertRaises(ar.AuditError) as ctx:
            ar.parse_pins("--index-url https://example.invalid/simple\n", "lock.txt")
        self.assertIn("lock.txt:1", str(ctx.exception))

    def test_lock_with_no_pins_is_an_error(self):
        with self.assertRaises(ar.AuditError):
            ar.parse_pins("# only a comment\n", "lock.txt")


class TestPlanRounds(unittest.TestCase):
    def test_distinct_names_share_one_round(self):
        pins = [ar.Pin("a", "1"), ar.Pin("b", "2")]
        self.assertEqual(ar.plan_rounds(pins), [[ar.Pin("a", "1"), ar.Pin("b", "2")]])

    def test_repeated_name_is_split_across_rounds(self):
        # rpds-py is pinned at two versions under complementary markers, and
        # pip-audit rejects a requirements file naming a package twice.
        pins = [ar.Pin("rpds-py", "0.30.0"), ar.Pin("a", "1"), ar.Pin("rpds-py", "2026.6.3")]
        self.assertEqual(
            ar.plan_rounds(pins),
            [[ar.Pin("a", "1"), ar.Pin("rpds-py", "0.30.0")], [ar.Pin("rpds-py", "2026.6.3")]],
        )

    def test_requirements_body_is_plain_pins(self):
        self.assertEqual(
            ar.pins_to_requirements([ar.Pin("a", "1"), ar.Pin("b", "2")]),
            "a==1\nb==2\n",
        )


class TestParsePipAuditResult(unittest.TestCase):
    """The subprocess contract: which exit codes mean what, and what the operator is told."""

    CLEAN = '{"dependencies": [], "fixes": []}'

    def test_exit_zero_with_a_report(self):
        self.assertEqual(
            ar.parse_pip_audit_result(0, self.CLEAN, ""), {"dependencies": [], "fixes": []}
        )

    def test_exit_one_with_a_report_is_vulnerabilities_found(self):
        # pip-audit exits 1 when it finds something; that is a verdict, not an error.
        payload = '{"dependencies": [{"name": "a", "version": "1", "vulns": []}], "fixes": []}'
        self.assertEqual(len(ar.parse_pip_audit_result(1, payload, "")["dependencies"]), 1)

    def test_exit_one_with_no_report_quotes_what_pip_audit_said(self):
        # --strict exits 1 with an empty stdout and the diagnosis on stderr. The
        # operator needs that line, not a JSON decoder complaint.
        stderr = (
            "ERROR:pip_audit._cli:nonesuch: Dependency not found on PyPI and "
            "could not be audited: nonesuch (1.0.0)"
        )
        with self.assertRaises(ar.AuditError) as ctx:
            ar.parse_pip_audit_result(1, "", stderr)
        self.assertIn("Dependency not found on PyPI", str(ctx.exception))

    def test_unexpected_exit_code_quotes_stderr(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.parse_pip_audit_result(2, "", "usage: pip-audit [-h]")
        self.assertIn("exited 2", str(ctx.exception))
        self.assertIn("usage: pip-audit", str(ctx.exception))

    def test_garbage_on_stdout_is_quoted_when_stderr_is_empty(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.parse_pip_audit_result(0, "not json at all", "")
        self.assertIn("not json at all", str(ctx.exception))

    def test_silent_failure_still_names_the_exit_code(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.parse_pip_audit_result(1, "", "")
        self.assertIn("(no output)", str(ctx.exception))


class TestRunPipAudit(unittest.TestCase):
    """The plumbing around the subprocess, with the subprocess itself stubbed out."""

    def test_pins_reach_pip_audit_in_a_requirements_file(self):
        seen = {}

        def fake_run(argv, **kwargs):
            seen["argv"] = argv
            seen["requirements"] = Path(argv[-1]).read_text(encoding="utf-8")
            return subprocess.CompletedProcess(argv, 0, '{"dependencies": []}', "")

        with unittest.mock.patch.object(ar.subprocess, "run", fake_run):
            self.assertEqual(ar.run_pip_audit("a==1\nb==2\n"), {"dependencies": []})

        self.assertEqual(seen["requirements"], "a==1\nb==2\n")
        self.assertEqual(seen["argv"][:3], [sys.executable, "-m", "pip_audit"])
        for flag in ("--no-deps", "--disable-pip", "--strict"):
            self.assertIn(flag, seen["argv"])
        self.assertEqual(seen["argv"][seen["argv"].index("--format") + 1], "json")

    def test_a_failing_subprocess_becomes_an_audit_error(self):
        def fake_run(argv, **kwargs):
            return subprocess.CompletedProcess(argv, 1, "", "ERROR:pip_audit._cli:boom")

        with unittest.mock.patch.object(ar.subprocess, "run", fake_run):
            with self.assertRaises(ar.AuditError) as ctx:
                ar.run_pip_audit("a==1\n")
        self.assertIn("boom", str(ctx.exception))


class TestFindingsFromReport(unittest.TestCase):
    def test_one_finding_per_vulnerability(self):
        payload = {
            "dependencies": [
                {"name": "clean", "version": "1.0", "vulns": []},
                {
                    "name": "MCP",
                    "version": "1.23.3",
                    "vulns": [vuln("PYSEC-1", "1.27.2", ("CVE-1",)), vuln("PYSEC-2")],
                },
            ]
        }
        findings = ar.findings_from_report(payload, "lock.txt")
        self.assertEqual([f.vuln_id for f in findings], ["PYSEC-1", "PYSEC-2"])
        self.assertEqual(findings[0].package, "mcp")
        self.assertEqual(findings[0].lock, "lock.txt")
        self.assertEqual(findings[0].fix_versions, ("1.27.2",))
        self.assertIn("CVE-1", findings[0].describe())


class IgnoreFileTestCase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmpdir = Path(self._tmp.name)

    def write_ignore(self, body: str) -> Path:
        path = self.tmpdir / "ignore.toml"
        path.write_text(body, encoding="utf-8")
        return path


VALID_ENTRY = """
[[ignore."scripts/lock.txt"]]
id = "PYSEC-1"
package = "somepkg"
reason = "unreachable here"
remove_when = "the upstream cap lifts"
"""


class TestLoadIgnores(IgnoreFileTestCase):
    def test_missing_file_ignores_nothing(self):
        self.assertEqual(ar.load_ignores(self.tmpdir / "absent.toml", {"scripts/lock.txt"}), [])

    def test_valid_entry(self):
        entries = ar.load_ignores(self.write_ignore(VALID_ENTRY), {"scripts/lock.txt"})
        self.assertEqual(len(entries), 1)
        self.assertEqual(entries[0].lock, "scripts/lock.txt")
        self.assertEqual(entries[0].vuln_id, "PYSEC-1")
        self.assertEqual(entries[0].package, "somepkg")

    def test_entry_filed_under_a_path_that_is_not_a_lock_is_an_error(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(VALID_ENTRY), {"scripts/other.txt"})
        self.assertIn("not a requirements lock in this tree", str(ctx.exception))

    def test_missing_required_field_is_an_error(self):
        body = VALID_ENTRY.replace('remove_when = "the upstream cap lifts"\n', "")
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("remove_when", str(ctx.exception))

    def test_blank_required_field_is_an_error(self):
        body = VALID_ENTRY.replace('reason = "unreachable here"', 'reason = "   "')
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("reason", str(ctx.exception))

    def test_unknown_field_is_an_error(self):
        body = VALID_ENTRY + 'expires = "2027-01-01"\n'
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("expires", str(ctx.exception))

    def test_duplicate_id_under_one_lock_is_an_error(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(VALID_ENTRY * 2), {"scripts/lock.txt"})
        self.assertIn("duplicate", str(ctx.exception))

    def test_unknown_top_level_table_is_an_error(self):
        body = VALID_ENTRY + "\n[settings]\nfail_on_stale = false\n"
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("settings", str(ctx.exception))

    def test_invalid_toml_is_an_error(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore("[[ignore.\n"), {"scripts/lock.txt"})
        self.assertIn("invalid TOML", str(ctx.exception))

    def test_lock_key_must_hold_an_array_of_tables(self):
        body = '[ignore]\n"scripts/lock.txt" = "PYSEC-1"\n'
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("array of tables", str(ctx.exception))

    # The three shapes below used to raise AttributeError. The file's whole job
    # is to be re-read by a human under time pressure; a traceback is a worse
    # thing to hand them than the messages every other branch produces.

    def test_ignore_must_be_a_table(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore('ignore = "oops"\n'), {"scripts/lock.txt"})
        self.assertIn("[ignore] must be a table", str(ctx.exception))

    def test_array_elements_must_be_tables(self):
        body = '[ignore]\n"scripts/lock.txt" = ["oops"]\n'
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("must be a table with the fields", str(ctx.exception))

    def test_non_string_field_is_an_error(self):
        body = VALID_ENTRY.replace('id = "PYSEC-1"', "id = 1")
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("non-string field(s): id", str(ctx.exception))


def entry(lock="lock.txt", vuln_id="PYSEC-1", package="somepkg") -> ar.IgnoreEntry:
    return ar.IgnoreEntry(lock=lock, vuln_id=vuln_id, package=package, reason="r", remove_when="w")


def finding(lock="lock.txt", vuln_id="PYSEC-1", package="somepkg", version="1.0") -> ar.Finding:
    return ar.Finding(
        lock=lock,
        package=package,
        version=version,
        vuln_id=vuln_id,
        fix_versions=("2.0",),
        aliases=(),
    )


class TestEvaluate(unittest.TestCase):
    def test_no_findings_and_no_entries_passes(self):
        report = ar.evaluate([("lock.txt", 3, 0)], [], [])
        self.assertFalse(report.failed)

    def test_finding_without_an_entry_fails(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [])
        self.assertTrue(report.failed)
        self.assertEqual(report.unignored, [finding()])

    def test_matching_entry_tolerates_the_finding(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [entry()])
        self.assertFalse(report.failed)
        self.assertEqual([f for _, f in report.honored], [finding()])

    def test_entry_no_longer_reported_is_stale_and_fails(self):
        # The property that keeps the list from only ever growing.
        report = ar.evaluate([("lock.txt", 3, 0)], [], [entry()])
        self.assertTrue(report.failed)
        self.assertEqual(report.stale, [entry()])

    def test_ignoring_is_per_lock(self):
        # An entry justified against one lock does not silence the same ID in
        # another; here it is both stale in its own lock and unignored in the other.
        report = ar.evaluate(
            [("lock.txt", 3, 0), ("other.txt", 3, 1)],
            [finding(lock="other.txt")],
            [entry(lock="lock.txt")],
        )
        self.assertTrue(report.failed)
        self.assertEqual(report.stale, [entry(lock="lock.txt")])
        self.assertEqual(report.unignored, [finding(lock="other.txt")])

    def test_entry_naming_the_wrong_package_fails(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [entry(package="elsewhere")])
        self.assertTrue(report.failed)
        self.assertEqual(len(report.mismatched), 1)
        self.assertEqual(report.honored, [])
        # Not also reported as having no entry: it has one, it is just wrong,
        # and "add a justified entry" would be the wrong instruction.
        self.assertEqual(report.unignored, [])

    def test_one_entry_covers_both_versions_of_a_package_pinned_twice(self):
        # A universal lock pins rpds-py at two versions under complementary
        # markers. The reachability argument an entry records is about how the
        # repo uses the package, not about a version, so one entry covers both
        # but both findings still appear in the report.
        both = [
            finding(package="rpds-py", version="0.30.0"),
            finding(package="rpds-py", version="2026.6.3"),
        ]
        report = ar.evaluate([("lock.txt", 3, 2)], both, [entry(package="rpds-py")])
        self.assertFalse(report.failed)
        self.assertEqual([f.version for _, f in report.honored], ["0.30.0", "2026.6.3"])
        self.assertEqual(report.unignored, [])

    def test_an_entry_for_one_package_does_not_cover_another_with_the_same_id(self):
        # Two packages, one shared advisory ID: naming one leaves the other
        # unignored rather than silently covering it.
        findings = [finding(package="somepkg"), finding(package="otherpkg")]
        report = ar.evaluate([("lock.txt", 3, 2)], findings, [entry(package="somepkg")])
        self.assertTrue(report.failed)
        self.assertEqual([f.package for _, f in report.honored], ["somepkg"])
        self.assertEqual([f.package for f in report.unignored], ["otherpkg"])


class TestFormatReport(unittest.TestCase):
    def test_stale_entry_report_names_the_removal_condition(self):
        report = ar.evaluate([("lock.txt", 3, 0)], [], [entry()])
        text = ar.format_report(report, "ignore.toml")
        self.assertIn("Stale ignore entries", text)
        self.assertIn("recorded as removable when: w", text)

    def test_unignored_finding_report_points_at_both_remedies(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [])
        text = ar.format_report(report, "ignore.toml")
        self.assertIn("no ignore entry", text)
        self.assertIn("Regenerate the lock", text)
        self.assertIn("ignore.toml", text)


class TestMain(IgnoreFileTestCase):
    """End-to-end runs over a synthetic repo tree, with pip-audit faked out."""

    def setUp(self):
        super().setUp()
        (self.tmpdir / "scripts" / "ci").mkdir(parents=True)
        (self.tmpdir / "scripts" / "requirements.txt").write_text(
            "clean==1.0 \\\n    --hash=sha256:abc\n", encoding="utf-8"
        )
        (self.tmpdir / "scripts" / "ci" / "requirements-tool.txt").write_text(
            "risky==1.23.3 \\\n    --hash=sha256:def\n", encoding="utf-8"
        )

    TOOL_ENTRY = (
        '[[ignore."scripts/ci/requirements-tool.txt"]]\n'
        'id = "PYSEC-1"\n'
        'package = "risky"\n'
        'reason = "no server is ever started"\n'
        'remove_when = "upstream relaxes its pin"\n'
    )

    def run_main(self, ignore_body: str | None, vulns: dict[str, list[dict]], *locks: str):
        argv = ["--root", str(self.tmpdir)]
        argv += ["--ignore-file", str(self.write_ignore(ignore_body or ""))]
        argv += [str(self.tmpdir / lock) for lock in locks]
        buffer = io.StringIO()
        with redirect_stdout(buffer), redirect_stderr(buffer):
            code = ar.main(argv, runner=fake_runner(vulns))
        return code, buffer.getvalue()

    def test_discovers_every_lock_and_passes_when_clean(self):
        code, out = self.run_main(None, {})
        self.assertEqual(code, 0)
        self.assertIn("Audited 2 requirements lock(s)", out)
        self.assertIn("scripts/requirements.txt", out)
        # Forward slashes on every platform: these are the keys the checked-in
        # ignore file uses, so they cannot depend on the OS separator.
        self.assertIn("scripts/ci/requirements-tool.txt", out)

    def test_unignored_finding_fails(self):
        code, out = self.run_main(None, {"risky": [vuln("PYSEC-1")]})
        self.assertEqual(code, 1)
        self.assertIn("no ignore entry", out)

    def test_ignored_finding_passes_and_prints_the_rationale(self):
        code, out = self.run_main(self.TOOL_ENTRY, {"risky": [vuln("PYSEC-1")]})
        self.assertEqual(code, 0)
        self.assertIn("no server is ever started", out)
        self.assertIn("upstream relaxes its pin", out)

    def test_ignore_entry_that_is_no_longer_reported_fails(self):
        code, out = self.run_main(self.TOOL_ENTRY, {})
        self.assertEqual(code, 1)
        self.assertIn("Stale ignore entries", out)

    def test_invalid_ignore_file_exits_two(self):
        code, _ = self.run_main('[[ignore."scripts/nope.txt"]]\nid = "X"\n', {})
        self.assertEqual(code, 2)

    def test_narrowing_to_one_lock_does_not_misread_the_other_locks_entries(self):
        # Naming a lock is the documented interface, and it used to exit 2 with
        # "not one of the audited locks" for every entry filed elsewhere.
        code, out = self.run_main(self.TOOL_ENTRY, {}, "scripts/requirements.txt")
        self.assertEqual(code, 0)
        self.assertIn("Audited 1 requirements lock(s)", out)
        self.assertIn("Not the full gate", out)
        self.assertIn("scripts/ci/requirements-tool.txt", out)

    def test_narrowing_still_enforces_the_entries_in_scope(self):
        code, out = self.run_main(self.TOOL_ENTRY, {}, "scripts/ci/requirements-tool.txt")
        self.assertEqual(code, 1)
        self.assertIn("Stale ignore entries", out)
        self.assertNotIn("Not the full gate", out)

    def test_a_path_that_is_no_lock_at_all_is_still_an_error_when_narrowed(self):
        body = '[[ignore."scripts/nope.txt"]]\nid = "X"\npackage = "p"\nreason = "r"\nremove_when = "w"\n'
        code, out = self.run_main(body, {}, "scripts/requirements.txt")
        self.assertEqual(code, 2)
        self.assertIn("not a requirements lock in this tree", out)

    def test_unparseable_lock_exits_two(self):
        (self.tmpdir / "scripts" / "requirements.txt").write_text("-e .\n", encoding="utf-8")
        code, _ = self.run_main(None, {})
        self.assertEqual(code, 2)


class TestRealIgnoreFile(unittest.TestCase):
    """The checked-in ignore file must satisfy the same validation CI applies."""

    def test_repo_ignore_file_parses_against_the_real_locks(self):
        root = ar.REPO_ROOT
        locks = {ar.relative_to_root(p, root) for p in ar.discover_locks(root)}
        entries = ar.load_ignores(root / ar.DEFAULT_IGNORE_FILE, locks)
        self.assertTrue(entries, "expected at least one ignore entry to be exercised")


if __name__ == "__main__":
    unittest.main()
