#!/usr/bin/env python3
"""Unit tests for audit_requirements.py.

No test reaches the network: pip-audit is replaced by a fake runner that
answers from a table of package name -> advisories, so the tests exercise the
parsing, ignore-matching and verdict logic rather than the vulnerability feed.
"""

import io
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
import audit_requirements as ar  # noqa: E402


def fake_runner(vulns_by_package: dict[str, list[dict]]):
    """Return a pip-audit stand-in that reports *vulns_by_package* for the pins it is given."""

    def run(requirements: str) -> dict:
        dependencies = []
        for line in requirements.splitlines():
            name, _, version = line.partition("==")
            dependencies.append(
                {
                    "name": name,
                    "version": version,
                    "vulns": vulns_by_package.get(name, []),
                }
            )
        return {"dependencies": dependencies, "fixes": []}

    return run


def vuln(vuln_id: str, fix: str = "9.9.9", aliases: tuple[str, ...] = ()) -> dict:
    return {"id": vuln_id, "fix_versions": [fix], "aliases": list(aliases)}


class TestNormalize(unittest.TestCase):
    def test_pep503_normalization(self):
        self.assertEqual(ar.normalize("Mdformat_GFM"), "mdformat-gfm")
        self.assertEqual(ar.normalize("ruamel.yaml"), "ruamel-yaml")
        self.assertEqual(ar.normalize("rpds-py"), "rpds-py")


class TestParsePins(unittest.TestCase):
    def test_reads_pins_and_skips_hashes_and_comments(self):
        text = (
            "# This file was autogenerated by uv\n"
            "certifi==2026.6.17 \\\n"
            "    --hash=sha256:abc \\\n"
            "    --hash=sha256:def\n"
            "    # via requests\n"
            "requests==2.34.2 \\\n"
            "    --hash=sha256:012\n"
        )
        self.assertEqual(
            ar.parse_pins(text, "lock.txt"),
            [ar.Pin("certifi", "2026.6.17"), ar.Pin("requests", "2.34.2")],
        )

    def test_marker_gated_pins_are_included(self):
        # The whole point of re-deriving the pin list: pip-audit would evaluate
        # these markers against the running interpreter and skip both.
        text = (
            "pywin32==311 ; sys_platform == 'win32' \\\n"
            "    --hash=sha256:abc\n"
            "tomli==2.4.1 ; python_full_version < '3.11' \\\n"
            "    --hash=sha256:def\n"
        )
        self.assertEqual(
            ar.parse_pins(text, "lock.txt"),
            [ar.Pin("pywin32", "311"), ar.Pin("tomli", "2.4.1")],
        )

    def test_names_are_normalized_and_duplicates_collapsed(self):
        text = "Ruamel.YAML==0.19.1\nruamel-yaml==0.19.1\n"
        self.assertEqual(ar.parse_pins(text, "lock.txt"), [ar.Pin("ruamel-yaml", "0.19.1")])

    def test_unrecognized_top_level_line_is_an_error(self):
        # Failing closed keeps a lock-format change from silently shrinking coverage.
        with self.assertRaises(ar.AuditError) as ctx:
            ar.parse_pins("--index-url https://example.invalid/simple\n", "lock.txt")
        self.assertIn("lock.txt:1", str(ctx.exception))

    def test_lock_with_no_pins_is_an_error(self):
        with self.assertRaises(ar.AuditError):
            ar.parse_pins("# only a comment\n", "lock.txt")


class TestPlanRounds(unittest.TestCase):
    def test_distinct_names_share_one_round(self):
        pins = [ar.Pin("a", "1"), ar.Pin("b", "2")]
        self.assertEqual(ar.plan_rounds(pins), [[ar.Pin("a", "1"), ar.Pin("b", "2")]])

    def test_repeated_name_is_split_across_rounds(self):
        # rpds-py is pinned at two versions under complementary markers, and
        # pip-audit rejects a requirements file naming a package twice.
        pins = [ar.Pin("rpds-py", "0.30.0"), ar.Pin("a", "1"), ar.Pin("rpds-py", "2026.6.3")]
        self.assertEqual(
            ar.plan_rounds(pins),
            [[ar.Pin("a", "1"), ar.Pin("rpds-py", "0.30.0")], [ar.Pin("rpds-py", "2026.6.3")]],
        )

    def test_requirements_body_is_plain_pins(self):
        self.assertEqual(
            ar.pins_to_requirements([ar.Pin("a", "1"), ar.Pin("b", "2")]),
            "a==1\nb==2\n",
        )


class TestFindingsFromReport(unittest.TestCase):
    def test_one_finding_per_vulnerability(self):
        payload = {
            "dependencies": [
                {"name": "clean", "version": "1.0", "vulns": []},
                {
                    "name": "MCP",
                    "version": "1.23.3",
                    "vulns": [vuln("PYSEC-1", "1.27.2", ("CVE-1",)), vuln("PYSEC-2")],
                },
            ]
        }
        findings = ar.findings_from_report(payload, "lock.txt")
        self.assertEqual([f.vuln_id for f in findings], ["PYSEC-1", "PYSEC-2"])
        self.assertEqual(findings[0].package, "mcp")
        self.assertEqual(findings[0].lock, "lock.txt")
        self.assertEqual(findings[0].fix_versions, ("1.27.2",))
        self.assertIn("CVE-1", findings[0].describe())


class IgnoreFileTestCase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmpdir = Path(self._tmp.name)

    def write_ignore(self, body: str) -> Path:
        path = self.tmpdir / "ignore.toml"
        path.write_text(body, encoding="utf-8")
        return path


VALID_ENTRY = """
[[ignore."scripts/lock.txt"]]
id = "PYSEC-1"
package = "somepkg"
reason = "unreachable here"
remove_when = "the upstream cap lifts"
"""


class TestLoadIgnores(IgnoreFileTestCase):
    def test_missing_file_ignores_nothing(self):
        self.assertEqual(ar.load_ignores(self.tmpdir / "absent.toml", {"scripts/lock.txt"}), [])

    def test_valid_entry(self):
        entries = ar.load_ignores(self.write_ignore(VALID_ENTRY), {"scripts/lock.txt"})
        self.assertEqual(len(entries), 1)
        self.assertEqual(entries[0].lock, "scripts/lock.txt")
        self.assertEqual(entries[0].vuln_id, "PYSEC-1")
        self.assertEqual(entries[0].package, "somepkg")

    def test_entry_filed_under_an_unaudited_lock_is_an_error(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(VALID_ENTRY), {"scripts/other.txt"})
        self.assertIn("not one of the audited locks", str(ctx.exception))

    def test_missing_required_field_is_an_error(self):
        body = VALID_ENTRY.replace('remove_when = "the upstream cap lifts"\n', "")
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("remove_when", str(ctx.exception))

    def test_blank_required_field_is_an_error(self):
        body = VALID_ENTRY.replace('reason = "unreachable here"', 'reason = "   "')
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("reason", str(ctx.exception))

    def test_unknown_field_is_an_error(self):
        body = VALID_ENTRY + 'expires = "2027-01-01"\n'
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("expires", str(ctx.exception))

    def test_duplicate_id_under_one_lock_is_an_error(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(VALID_ENTRY * 2), {"scripts/lock.txt"})
        self.assertIn("duplicate", str(ctx.exception))

    def test_unknown_top_level_table_is_an_error(self):
        body = VALID_ENTRY + "\n[settings]\nfail_on_stale = false\n"
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("settings", str(ctx.exception))

    def test_invalid_toml_is_an_error(self):
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore("[[ignore.\n"), {"scripts/lock.txt"})
        self.assertIn("invalid TOML", str(ctx.exception))

    def test_lock_key_must_hold_an_array_of_tables(self):
        body = '[ignore]\n"scripts/lock.txt" = "PYSEC-1"\n'
        with self.assertRaises(ar.AuditError) as ctx:
            ar.load_ignores(self.write_ignore(body), {"scripts/lock.txt"})
        self.assertIn("array of tables", str(ctx.exception))


def entry(lock="lock.txt", vuln_id="PYSEC-1", package="somepkg") -> ar.IgnoreEntry:
    return ar.IgnoreEntry(lock=lock, vuln_id=vuln_id, package=package, reason="r", remove_when="w")


def finding(lock="lock.txt", vuln_id="PYSEC-1", package="somepkg") -> ar.Finding:
    return ar.Finding(
        lock=lock,
        package=package,
        version="1.0",
        vuln_id=vuln_id,
        fix_versions=("2.0",),
        aliases=(),
    )


class TestEvaluate(unittest.TestCase):
    def test_no_findings_and_no_entries_passes(self):
        report = ar.evaluate([("lock.txt", 3, 0)], [], [])
        self.assertFalse(report.failed)

    def test_finding_without_an_entry_fails(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [])
        self.assertTrue(report.failed)
        self.assertEqual(report.unignored, [finding()])

    def test_matching_entry_tolerates_the_finding(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [entry()])
        self.assertFalse(report.failed)
        self.assertEqual([f for _, f in report.honored], [finding()])

    def test_entry_no_longer_reported_is_stale_and_fails(self):
        # The property that keeps the list from only ever growing.
        report = ar.evaluate([("lock.txt", 3, 0)], [], [entry()])
        self.assertTrue(report.failed)
        self.assertEqual(report.stale, [entry()])

    def test_ignoring_is_per_lock(self):
        # An entry justified against one lock does not silence the same ID in
        # another; here it is both stale in its own lock and unignored in the other.
        report = ar.evaluate(
            [("lock.txt", 3, 0), ("other.txt", 3, 1)],
            [finding(lock="other.txt")],
            [entry(lock="lock.txt")],
        )
        self.assertTrue(report.failed)
        self.assertEqual(report.stale, [entry(lock="lock.txt")])
        self.assertEqual(report.unignored, [finding(lock="other.txt")])

    def test_entry_naming_the_wrong_package_fails(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [entry(package="elsewhere")])
        self.assertTrue(report.failed)
        self.assertEqual(len(report.mismatched), 1)
        self.assertEqual(report.honored, [])
        self.assertEqual(report.unignored, [finding()])


class TestFormatReport(unittest.TestCase):
    def test_stale_entry_report_names_the_removal_condition(self):
        report = ar.evaluate([("lock.txt", 3, 0)], [], [entry()])
        text = ar.format_report(report, "ignore.toml")
        self.assertIn("Stale ignore entries", text)
        self.assertIn("recorded as removable when: w", text)

    def test_unignored_finding_report_points_at_both_remedies(self):
        report = ar.evaluate([("lock.txt", 3, 1)], [finding()], [])
        text = ar.format_report(report, "ignore.toml")
        self.assertIn("no ignore entry", text)
        self.assertIn("Regenerate the lock", text)
        self.assertIn("ignore.toml", text)


class TestMain(IgnoreFileTestCase):
    """End-to-end runs over a synthetic repo tree, with pip-audit faked out."""

    def setUp(self):
        super().setUp()
        (self.tmpdir / "scripts" / "ci").mkdir(parents=True)
        (self.tmpdir / "scripts" / "requirements.txt").write_text(
            "clean==1.0 \\\n    --hash=sha256:abc\n", encoding="utf-8"
        )
        (self.tmpdir / "scripts" / "ci" / "requirements-tool.txt").write_text(
            "risky==1.23.3 \\\n    --hash=sha256:def\n", encoding="utf-8"
        )

    def run_main(self, ignore_body: str | None, vulns: dict[str, list[dict]]):
        argv = ["--root", str(self.tmpdir)]
        argv += ["--ignore-file", str(self.write_ignore(ignore_body or ""))]
        buffer = io.StringIO()
        with redirect_stdout(buffer), redirect_stderr(buffer):
            code = ar.main(argv, runner=fake_runner(vulns))
        return code, buffer.getvalue()

    def test_discovers_every_lock_and_passes_when_clean(self):
        code, out = self.run_main(None, {})
        self.assertEqual(code, 0)
        self.assertIn("Audited 2 requirements lock(s)", out)
        self.assertIn("scripts/requirements.txt", out)
        self.assertIn(os.path.join("scripts", "ci", "requirements-tool.txt"), out)

    def test_unignored_finding_fails(self):
        code, out = self.run_main(None, {"risky": [vuln("PYSEC-1")]})
        self.assertEqual(code, 1)
        self.assertIn("no ignore entry", out)

    def test_ignored_finding_passes_and_prints_the_rationale(self):
        body = (
            '[[ignore."scripts/ci/requirements-tool.txt"]]\n'
            'id = "PYSEC-1"\n'
            'package = "risky"\n'
            'reason = "no server is ever started"\n'
            'remove_when = "upstream relaxes its pin"\n'
        )
        code, out = self.run_main(body, {"risky": [vuln("PYSEC-1")]})
        self.assertEqual(code, 0)
        self.assertIn("no server is ever started", out)
        self.assertIn("upstream relaxes its pin", out)

    def test_ignore_entry_that_is_no_longer_reported_fails(self):
        body = (
            '[[ignore."scripts/ci/requirements-tool.txt"]]\n'
            'id = "PYSEC-1"\n'
            'package = "risky"\n'
            'reason = "no server is ever started"\n'
            'remove_when = "upstream relaxes its pin"\n'
        )
        code, out = self.run_main(body, {})
        self.assertEqual(code, 1)
        self.assertIn("Stale ignore entries", out)

    def test_invalid_ignore_file_exits_two(self):
        code, _ = self.run_main('[[ignore."scripts/nope.txt"]]\nid = "X"\n', {})
        self.assertEqual(code, 2)

    def test_unparseable_lock_exits_two(self):
        (self.tmpdir / "scripts" / "requirements.txt").write_text("-e .\n", encoding="utf-8")
        code, _ = self.run_main(None, {})
        self.assertEqual(code, 2)


class TestRealIgnoreFile(unittest.TestCase):
    """The checked-in ignore file must satisfy the same validation CI applies."""

    def test_repo_ignore_file_parses_against_the_real_locks(self):
        root = ar.REPO_ROOT
        locks = {ar.relative_to_root(p, root) for p in ar.discover_locks(root)}
        entries = ar.load_ignores(root / ar.DEFAULT_IGNORE_FILE, locks)
        self.assertTrue(entries, "expected at least one ignore entry to be exercised")


if __name__ == "__main__":
    unittest.main()
